version: '1.0'

services:
  app:
    image: ghcr.io/fmdelgado/dracoonpy:master
    volumes:
      - ./config.toml:/app/.streamlit/config.toml
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    ports:
        - 8041:8031
    container_name: dracoon



